---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---

# Example of plotly

We're gonna look at Instacart data.

```{r}
library(tidyverse)
library(plotly)
library(p8105.datasets)
data(ny_noaa)
```
# Plotly Plots
## scatterplot
```{r}
temp_scatter_plot <- ny_noaa |> 
  filter(!is.na(tmax) & !is.na(tmin)) |>
  sample_n(1000) |> 
  plot_ly(
    x = ~tmax, 
    y = ~tmin, 
    type = "scatter", 
    mode = "markers",
    marker = list(color = "purple", size = 5, opacity = 0.5)
  ) 

temp_scatter_plot
```
## Barplot
```{r}
precip_agg <- ny_noaa |> 
  filter(!is.na(prcp)) |> 
  group_by(date) |>     
  summarise(total_precip = sum(prcp, na.rm = TRUE)) 

precip_plot <- precip_agg |> 
  plot_ly(
    x = ~date, 
    y = ~total_precip, 
    type = "bar",
    marker = list(color = "skyblue")
  )

precip_plot
```
## Box plot
```{r}
boxplot_temp <- ny_noaa |> 
  filter(!is.na(tmax) & !is.na(tmin)) |> 
  sample_n(1000) |> 
  plot_ly() |> 
  add_boxplot(
    y = ~tmax, 
    name = "Max Temperature (°C)", 
    boxpoints = "all", 
    marker = list(color = "lightblue"), 
    boxmean = TRUE  # Show the mean
  ) |> 
  add_boxplot(
    y = ~tmin, 
    name = "Min Temperature (°C)", 
    boxpoints = "all", 
    marker = list(color = "lightcoral"), 
    boxmean = TRUE  # Show the mean
  ) 

boxplot_temp
```


